### ISSUE TITLE
「ボタン3」の動作不良

### ISSUE THREAD

**Issue by Naka-nishi-s** [noyasan-3702/-#2]
添付の動画の通り、「ボタン3」を押した際に、「ボタン4」の色が変化しています。
「ボタン3」押下時にはボタン3の色が変化、「ボタン4」押下時にはボタン4の色が変化するように修正しましょう。

https://github.com/user-attachments/assets/818606d7-c1a1-452a-b2e0-a4c370ebbd79

**Comment by Naka-nishi-s** [comment]
以下コミットで修正を確認
https://github.com/noyasan-3702/-/commit/6790092562e59b7ce0c534406b97f8e766d7669f

**Comment by noyasan-3702** [comment]
完了しました！
